### ISSUE TITLE
How to run the model, and UnicodeDecodeError in render_highlight_patching.py

### ISSUE THREAD

**Issue by wyf18** [gmy2013/FOSTERER#1]
I can't figure out how to precess the data and train the model, and when I run render_highlight_patching.py, it reports an error：

```
(render_highlight_patching.py:3635232): Gdk-CRITICAL **: 22:02:10.173: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
/home/wuyf/doc_test/FOSTERER/visualize_patching/test.java
Traceback (most recent call last):
  File "/home/wuyf/doc_test/FOSTERER/visualize_patching/render_highlight_patching.py", line 121, in <module>
    from_to_file("/home/wuyf/doc_test/FOSTERER/visualize_patching/test.java", "generate.png", "Java") # Replace with the path to the source code file and path to store the png
  File "/home/wuyf/doc_test/FOSTERER/visualize_patching/render_highlight_patching.py", line 22, in from_to_file
    image = render(code, lang)
  File "/home/wuyf/doc_test/FOSTERER/visualize_patching/render_highlight_patching.py", line 90, in render
    image_raw = imgkit.from_string(html_page, False, options)
  File "/home/wuyf/.local/lib/python3.8/site-packages/imgkit/api.py", line 108, in from_string
    return rtn.to_img(output_path)
  File "/home/wuyf/.local/lib/python3.8/site-packages/imgkit/imgkit.py", line 242, in to_img
    stderr = stderr.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
I would really like to know how to fix this error, thanks!

**Comment by gmy2013** [comment]
Thanks for your interest on our work. It seems that the UnicodeDecodeError is caused by the wrongly decoding of .PNG header. This step is just for convert the saved html to image. You can try to exploit html2image instead of imgkit:
from html2image import Html2Image
hti = Html2Image()
css = "body {background: white;}"
hti.screenshot(html_str=html_page, css_str=css, save_as=out_path)
The function above is the same as that: 
image_raw = imgkit.from_string(html_page, False, options)
return Image.open(io.BytesIO(image_raw))
After that, you will get the visual rendering of the input code snippet.
As for how to process the data and train the model, we will update the readme file for a detailed illustration soon.
